import type { ReactNode } from 'react';
import { Field as FluentField } from '@fluentui/react-components';
import type { FieldProps as FluentFieldProps } from '@fluentui/react-components';
import { SstTooltip } from '../Tooltip/SstTooltip';

export interface FieldProps extends FluentFieldProps {
  dica?: ReactNode;
}

const dicasExatas: Record<string, string> = {
  'Ação a ser realizada': 'Descreva exatamente o que precisa ser feito para corrigir, prevenir ou tratar o problema. Escreva como uma tarefa executável, não apenas como uma observação.',
  Afastamento: 'Informe se a ocorrência gerou afastamento do trabalhador. Essa informação impacta indicadores de segurança e relatórios de acidente.',
  Ano: 'Informe o ano de referência do registro, usando quatro dígitos.',
  'Ano de referência': 'Informe o ano que será usado como base para o evento, dimensionamento ou controle.',
  Aprovação: 'Informe a situação ou responsável pela aprovação deste registro.',
  'Arquivo (imagem JPEG/PNG, PDF ou Word)': 'Anexe o material de apoio no formato correto. Use PDF ou Word para documentos e JPEG/PNG para imagens.',
  Artigo: 'Informe o artigo, item ou trecho da norma que fundamenta este requisito.',
  'ASO vinculado (opcional)': 'Selecione o ASO relacionado quando este exame ou aptidão fizer parte de um ASO já cadastrado.',
  Atendimento: 'Descreva o atendimento prestado após a ocorrência, como primeiros socorros, encaminhamento médico ou acompanhamento.',
  'Atendimento prestado': 'Registre qual atendimento foi dado ao trabalhador logo após o acidente ou incidente.',
  'Atividade crítica': 'Selecione a atividade crítica relacionada à APR ou permissão, como trabalho em altura, espaço confinado, içamento ou energia perigosa.',
  'Atividades do dia': 'Liste as atividades previstas ou realizadas no dia. Isso ajuda a relacionar DDS, riscos, evidências e participantes.',
  'Buscar por nome ou matrícula': 'Digite parte do nome ou matrícula para localizar rapidamente o trabalhador.',
  'Buscar por nome, função ou obra': 'Digite nome, função ou obra para filtrar a lista de trabalhadores.',
  Cargo: 'Informe o cargo ou papel exercido pela pessoa neste registro.',
  CAT: 'Informe se existe Comunicação de Acidente de Trabalho associada ao acidente.',
  CRM: 'Informe o CRM do médico responsável pelo exame ou ASO.',
  Curso: 'Selecione o curso ou treinamento realizado pelo trabalhador ou turma.',
  'Data da avaliação': 'Informe a data em que a avaliação foi realizada.',
  'Data da convocação': 'Informe a data em que a convocação foi emitida.',
  'Data da inspeção': 'Informe a data em que a inspeção foi realizada.',
  'Data da remoção': 'Informe a data em que o item foi removido do local.',
  'Data da reunião': 'Informe a data em que a reunião ocorreu ou ocorrerá.',
  'Data da revisão': 'Informe a data em que a revisão foi realizada.',
  'Data da votação': 'Informe a data prevista ou realizada para a votação.',
  'Data de elaboração': 'Informe a data em que o documento foi elaborado.',
  'Data de emissão': 'Informe a data em que o documento, certificado ou ASO foi emitido.',
  'Data do exame': 'Informe a data em que o exame ocupacional foi realizado.',
  Deliberações: 'Registre as decisões tomadas na reunião, incluindo responsáveis e encaminhamentos quando houver.',
  'Descreva o tipo de trabalho (Outro)': 'Quando o tipo de trabalho não existir na lista, descreva aqui o serviço de forma simples e objetiva.',
  'Descrição da etapa': 'Explique o que acontece nesta etapa do fluxo ou processo.',
  'Descrição do item': 'Descreva o item que deve ser verificado, entregue, tratado ou cadastrado.',
  'Descrição do ponto verificado': 'Escreva o que será avaliado no checklist. Use uma frase objetiva que o técnico consiga responder em campo.',
  Destinatário: 'Selecione quem deve receber o alerta, cobrança ou comunicação.',
  'Detalhes da localização': 'Explique onde fica a área ou ponto dentro da obra, incluindo referência visual quando necessário.',
  'Evidência anterior': 'Anexe ou visualize a evidência registrada antes da correção.',
  'Evidência posterior': 'Anexe ou visualize a evidência depois da correção para comprovar o tratamento.',
  'Evidências fotográficas': 'Informe ou acompanhe a quantidade de fotos anexadas como evidência da atividade.',
  Fabricante: 'Informe o fabricante do EPI, EPC ou item cadastrado.',
  'Fonte / circunstância': 'Descreva de onde veio a informação ou em qual circunstância a ocorrência aconteceu.',
  'Funcionários expostos': 'Informe quais trabalhadores estão expostos ao risco, atividade ou condição avaliada.',
  'Funções contempladas': 'Selecione as funções às quais este requisito, treinamento, EPI ou risco se aplica.',
  'Houve afastamento?': 'Marque se o trabalhador ficou afastado por causa da ocorrência. Se sim, informe também os dias de afastamento.',
  'ID do responsável SST (opcional)': 'Use somente quando for necessário informar manualmente o identificador técnico do responsável SST.',
  'ID do usuário (GUID)': 'Campo técnico: informe o identificador GUID do usuário somente quando solicitado por suporte ou administração.',
  'ID do usuário aprovador (GUID)': 'Campo técnico: informe o GUID do usuário que fará a aprovação.',
  'ID do usuário emitente/liberador (GUID)': 'Campo técnico: informe o GUID do usuário que emite ou libera a permissão.',
  'ID do usuário que encerra (GUID)': 'Campo técnico: informe o GUID do usuário responsável pelo encerramento.',
  Instituição: 'Informe a instituição responsável pelo treinamento ou emissão.',
  'Instituição / instrutor': 'Informe a instituição, empresa ou instrutor responsável pelo treinamento.',
  'Instituição/instrutor': 'Informe a instituição, empresa ou instrutor responsável pelo treinamento.',
  'Máquinas / Equip.': 'Informe as máquinas, equipamentos ou ferramentas envolvidos na atividade. Exemplo: betoneira, serra mármore, andaime, plataforma elevatória, furadeira ou escavadeira.',
  Médico: 'Informe o médico responsável pelo exame, ASO ou avaliação.',
  'Médico responsável': 'Informe o médico responsável pela avaliação ocupacional.',
  'Medidas de prevenção / controle': 'Descreva as medidas que reduzem ou controlam o risco, como EPC, EPI, procedimento, isolamento, sinalização ou treinamento.',
  'Membro que inspecionou': 'Selecione o membro responsável por realizar ou registrar a inspeção.',
  Mês: 'Selecione o mês de referência do registro.',
  'Motivo (feriado, folga, obra parada etc.)': 'Explique por que não houve atividade normal neste dia, como feriado, folga, chuva, obra parada ou outro motivo operacional.',
  'Motivo da reprovação': 'Explique por que o item foi reprovado, devolvido ou considerado inadequado.',
  'Níveis de probabilidade': 'Cadastre os níveis usados para medir a chance de o risco acontecer.',
  'Níveis de severidade': 'Cadastre os níveis usados para medir a consequência caso o risco aconteça.',
  'Nível de risco': 'Selecione o nível final do risco conforme a matriz adotada.',
  'Nome do checklist': 'Informe um nome fácil de reconhecer. Exemplo: Inspeção de alojamento, checklist de andaime ou verificação de EPI.',
  'Nome do Documento': 'Informe o nome que identifica o documento para consulta e rastreabilidade.',
  'Nome do PGR': 'Informe o nome do Programa de Gerenciamento de Riscos que será exibido nas listas e documentos.',
  'Nova validade': 'Informe a nova data de validade após revalidação ou prorrogação.',
  Ordem: 'Informe a posição em que este item deve aparecer na lista ou checklist.',
  'P (probabilidade inicial)': 'Informe a probabilidade antes dos controles. Use a escala definida na matriz de risco.',
  'P res. (probabilidade residual)': 'Informe a probabilidade que permanece depois de aplicar as medidas de controle.',
  Palestrante: 'Informe quem irá conduzir a palestra, DDS ou treinamento.',
  Papel: 'Selecione o papel ou responsabilidade da pessoa no processo.',
  Participantes: 'Selecione os trabalhadores que participaram da atividade, treinamento, DDS ou reunião.',
  'Perigo / evento perigoso': 'Descreva a fonte de perigo e o evento indesejado que pode acontecer.',
  Periodicidades: 'Informe os períodos ou frequências exigidos para repetição, renovação ou controle.',
  'PGR / Procedimento ref.': 'Informe o PGR, procedimento ou documento de referência usado como base.',
  'Plano de ação': 'Descreva o plano para corrigir a pendência, reduzir o risco ou tratar a não conformidade.',
  'Pontos verificados respondidos': 'Mostra quantos itens do checklist já foram respondidos. Use para acompanhar se a inspeção está completa antes de finalizar.',
  'Possíveis lesões / agravos / danos': 'Descreva os danos possíveis caso o perigo se materialize, como queda, corte, queimadura, intoxicação ou dano material.',
  'Prazo para tratamento': 'Informe até quando o alerta ou pendência deve ser tratado.',
  'Presenças confirmadas': 'Mostra quantos participantes já tiveram presença confirmada por assinatura ou registro.',
  'Próxima revisão': 'Informe quando este documento ou cadastro deve ser revisado novamente.',
  Resultado: 'Informe o resultado da avaliação, exame, inspeção ou verificação.',
  'Risco / condição': 'Descreva a condição de risco que exige controle antes ou durante a atividade.',
  'Risco identificado': 'Informe o risco encontrado na atividade, ambiente ou processo.',
  'Riscos considerados': 'Liste os riscos avaliados para esta decisão, documento ou atividade.',
  'S (severidade inicial)': 'Informe a severidade antes dos controles. Use a escala definida na matriz de risco.',
  'S res. (severidade residual)': 'Informe a severidade que permanece depois de aplicar as medidas de controle.',
  'Seção (opcional)': 'Informe uma seção para agrupar itens do checklist, como Documentação, Ambiente, Equipamentos ou Evidências.',
  Suplentes: 'Informe a quantidade de membros suplentes.',
  Titulares: 'Informe a quantidade de membros titulares.',
  Suspensão: 'Informe dados relacionados à suspensão da permissão ou atividade.',
  Tema: 'Informe o tema principal do evento, DDS, SIPAT ou treinamento.',
  'Tema da palestra': 'Informe o assunto principal que será apresentado.',
  'Tema livre (opcional)': 'Use quando o tema do DDS não estiver no catálogo. Escreva um assunto claro para o registro.',
  'Tema/problema': 'Informe o tema ou problema principal que será tratado.',
  Versão: 'Informe a versão do documento, procedimento ou cadastro.',
  'Visto do consórcio/responsável': 'Registre o visto, nome ou confirmação do responsável pelo recebimento/validação.',
};

const dicasPorRotulo: Array<[RegExp, string]> = [
  [/checklist/i, 'Escolha o modelo de checklist que será usado na inspeção. Ele define quais perguntas, itens de verificação e evidências deverão ser preenchidos durante a execução.'],
  [/aso/i, 'Selecione ou informe o ASO relacionado. Use este campo para vincular aptidão, exame ocupacional e validade médica do trabalhador.'],
  [/aptid[aã]o|apto|inapto/i, 'Informe o resultado de aptidão ocupacional do trabalhador para a função ou atividade avaliada.'],
  [/exames? previstos?/i, 'Liste os exames ocupacionais exigidos para este programa, função ou avaliação.'],
  [/tipo de exame/i, 'Selecione se o exame é admissional, periódico, demissional, retorno ao trabalho, mudança de risco ou outro tipo disponível.'],
  [/resultado/i, 'Informe o resultado final da avaliação, exame, inspeção ou verificação.'],
  [/obra/i, 'Selecione a obra onde este registro será realizado. Essa escolha organiza os dados por contrato/local e ajuda a filtrar responsáveis, atividades e relatórios depois.'],
  [/m[aá]quinas?\s*\/?\s*equip|equipamentos?/i, 'Informe as máquinas, equipamentos ou ferramentas envolvidos na atividade.'],
  [/ferramentas?/i, 'Informe as ferramentas que serão usadas ou avaliadas neste registro.'],
  [/empresa executante|empresa terceirizada/i, 'Informe a empresa responsável por executar a atividade ou serviço.'],
  [/cliente/i, 'Informe o cliente vinculado à obra ou contrato.'],
  [/endere[cç]o/i, 'Informe o endereço completo da obra ou local cadastrado.'],
  [/cidade/i, 'Informe a cidade onde a obra ou unidade está localizada.'],
  [/^uf$/i, 'Informe a sigla do estado, com duas letras.'],
  [/cnpj/i, 'Informe o CNPJ da obra, cliente ou empresa, usando apenas números quando possível.'],
  [/cnae/i, 'Informe o CNAE usado para enquadramento da atividade econômica.'],
  [/grau de risco/i, 'Selecione o grau de risco da atividade econômica conforme o enquadramento aplicável.'],
  [/funcion[aá]rio|trabalhador|participante/i, 'Selecione a pessoa correta para vincular o registro. Use esse campo para indicar quem recebeu o item, participou da atividade, assinou ou está envolvido na ocorrência.'],
  [/fun[cç][aã]o|cargo/i, 'Informe ou selecione a função exercida pelo trabalhador. Essa informação ajuda a aplicar treinamentos, EPIs, riscos e requisitos exigidos para o cargo.'],
  [/encarregado/i, 'Selecione o encarregado responsável por acompanhar a equipe ou atividade no campo.'],
  [/equipe executante|equipe/i, 'Informe a equipe ou os responsáveis que executarão a atividade. Inclua apenas pessoas diretamente envolvidas no serviço.'],
  [/atividade \(opcional\)/i, 'Selecione a atividade quando a inspeção, risco ou registro estiver ligado a um serviço específico. Se não houver atividade definida, deixe em branco.'],
  [/atividade/i, 'Informe a atividade executada, inspecionada ou vinculada ao registro. Descreva ou selecione o serviço real realizado em campo.'],
  [/setor|[aá]rea/i, 'Informe a área, setor ou frente de serviço onde o item se aplica.'],
  [/frente de servi[cç]o/i, 'Informe a frente de serviço onde o DDS, inspeção ou atividade será realizado.'],
  [/localiza[cç][aã]o/i, 'Descreva a localização de forma suficiente para a equipe encontrar o ponto correto.'],
  [/local|instala[cç][oõ]es/i, 'Informe o local físico com detalhe suficiente para outra pessoa encontrar o ponto depois, como bloco, pavimento, frente, sala, equipamento ou área da obra.'],
  [/data de admiss[aã]o/i, 'Informe a data em que o trabalhador iniciou vínculo com a empresa ou obra.'],
  [/data de entrega/i, 'Informe a data em que o item foi entregue ao trabalhador.'],
  [/data de instala[cç][aã]o/i, 'Informe a data em que o EPC foi instalado no local.'],
  [/data do treinamento|data de realiza[cç][aã]o/i, 'Informe a data em que o treinamento foi realizado.'],
  [/previs[aã]o de t[eé]rmino|t[eé]rmino da vig[eê]ncia/i, 'Informe a data prevista para encerramento ou fim de validade.'],
  [/in[ií]cio da semana/i, 'Informe a data inicial da semana planejada.'],
  [/data in[ií]cio|in[ií]cio/i, 'Informe a data de início.'],
  [/data fim|fim/i, 'Informe a data final.'],
  [/prazo/i, 'Informe a data limite para conclusão ou tratamento.'],
  [/validade/i, 'Informe a data ou período em que este item permanece válido.'],
  [/data/i, 'Informe a data do evento, entrega, inspeção ou registro. Use o formato dd/mm/aaaa.'],
  [/hora|hor[aá]rio/i, 'Informe o horário de início, fim ou ocorrência da atividade.'],
  [/status|situa[cç][aã]o/i, 'Selecione a situação atual do item. Use este campo para indicar se está ativo, pendente, vencido, concluído, bloqueado ou em tratamento, conforme as opções disponíveis.'],
  [/validar como/i, 'Selecione qual usuário ou responsável será usado para registrar a validação desta etapa.'],
  [/libera[cç][aã]o/i, 'Informe os dados da liberação da atividade ou permissão, incluindo quem liberou e quando.'],
  [/suspens[aã]o/i, 'Informe os dados da suspensão quando a atividade precisar ser interrompida por segurança, prazo ou condição operacional.'],
  [/encerramento/i, 'Informe os dados de encerramento quando a atividade, permissão ou ação estiver finalizada.'],
  [/origem/i, 'Selecione de onde a ocorrência, alerta ou não conformidade se originou.'],
  [/categoria/i, 'Informe a categoria usada para organizar e localizar este item depois.'],
  [/motivo da devolu[cç][aã]o/i, 'Explique por que a ação está sendo devolvida para ajuste.'],
  [/motivo da suspens[aã]o/i, 'Explique por que a permissão ou atividade está sendo suspensa.'],
  [/motivo/i, 'Selecione ou descreva o motivo do registro.'],
  [/tipo de entidade|id da entidade/i, 'Informe a referência técnica usada para ligar este registro a outra entidade do sistema.'],
  [/tipo/i, 'Selecione o tipo que melhor classifica este registro. Essa escolha ajuda o sistema a separar relatórios, alertas e filtros por categoria de ocorrência.'],
  [/severidade|gravidade|prioridade|risco/i, 'Selecione o nível conforme o impacto ou criticidade do caso.'],
  [/riscos? \(separados por v[ií]rgula\)/i, 'Liste os riscos associados, separando cada um por vírgula.'],
  [/requisitos? \(separados por v[ií]rgula\)/i, 'Liste os requisitos aplicáveis, separando cada um por vírgula.'],
  [/perigo/i, 'Informe o perigo ou fonte de dano relacionada ao requisito.'],
  [/controle complementar/i, 'Descreva o controle adicional necessário para reduzir o risco.'],
  [/medidas? de preven[cç][aã]o|controle/i, 'Descreva as medidas que reduzem o risco, como bloqueio, isolamento, sinalização, EPC, EPI, procedimento ou treinamento.'],
  [/a[cç][aã]o a ser realizada|descri[cç][aã]o da a[cç][aã]o/i, 'Descreva a ação que deve ser executada para tratar o item.'],
  [/descri[cç][aã]o da atividade/i, 'Descreva o serviço que será executado, com detalhes suficientes para análise.'],
  [/descri[cç][aã]o da conclus[aã]o/i, 'Registre o que foi feito para concluir a ação.'],
  [/observa[cç][oõ]es de encerramento/i, 'Registre observações finais sobre o encerramento.'],
  [/justificativa do prazo/i, 'Explique por que este prazo foi definido ou alterado.'],
  [/causas identificadas/i, 'Descreva as causas levantadas durante a investigação.'],
  [/metodologia de investiga[cç][aã]o/i, 'Informe a metodologia usada para investigar o acidente ou ocorrência.'],
  [/pauta/i, 'Informe os assuntos que serão tratados na reunião.'],
  [/programa[cç][aã]o/i, 'Descreva a programação prevista para o evento ou atividade.'],
  [/conte[uú]do program[aá]tico/i, 'Liste os tópicos que compõem o conteúdo do treinamento.'],
  [/texto de apoio/i, 'Informe uma orientação complementar para ajudar no preenchimento da pergunta.'],
  [/pergunta/i, 'Escreva a pergunta que será exibida no questionário.'],
  [/descri[cç][aã]o|observa[cç][oõ]es/i, 'Descreva os fatos principais com clareza: o que aconteceu, onde ocorreu, quem está envolvido e qual ação ou contexto precisa ficar registrado.'],
  [/respons[aá]vel|instrutor|t[eé]cnico/i, 'Selecione quem ficará responsável por acompanhar, executar, validar ou responder por este registro. Essa pessoa pode aparecer em cobranças, assinaturas e relatórios.'],
  [/executor/i, 'Selecione quem ficará responsável por executar a ação.'],
  [/destinat[aá]rio/i, 'Selecione quem deve receber ou tratar este alerta.'],
  [/titulares/i, 'Informe a quantidade de representantes titulares previstos.'],
  [/suplentes/i, 'Informe a quantidade de representantes suplentes previstos.'],
  [/dias de afastamento/i, 'Informe quantos dias o trabalhador ficou afastado por causa do acidente.'],
  [/dias debitados/i, 'Informe os dias debitados conforme a NBR 14280, quando aplicável.'],
  [/dias de anteced[eê]ncia/i, 'Informe com quantos dias de antecedência o alerta deve ser gerado.'],
  [/horas-homem trabalhadas|hht/i, 'Informe o total de horas trabalhadas pela equipe no período.'],
  [/carga hor[aá]ria/i, 'Informe a duração do treinamento em horas.'],
  [/vida [uú]til/i, 'Informe por quantos meses o item pode ser usado antes de troca ou revisão.'],
  [/quantidade|qtd|saldo|novo saldo|n[uú]mero/i, 'Informe o valor numérico que representa este campo.'],
  [/n[ºo] do ca|validade do ca/i, 'Informe os dados do Certificado de Aprovação do equipamento.'],
  [/n[ºo] lista de presen[cç]a/i, 'Informe o número da lista de presença vinculada ao treinamento.'],
  [/registro profissional/i, 'Informe o registro profissional do instrutor ou responsável técnico.'],
  [/c[oó]digo cbo/i, 'Informe o código CBO correspondente à função.'],
  [/c[oó]digo/i, 'Informe um código curto para identificar este cadastro.'],
  [/nome|t[ií]tulo/i, 'Informe um nome claro para identificar este registro.'],
  [/email|e-mail/i, 'Informe um endereço de e-mail válido.'],
  [/cpf/i, 'Informe o CPF com 11 dígitos.'],
  [/matr[ií]cula/i, 'Informe a matrícula do trabalhador.'],
  [/v[ií]nculo/i, 'Selecione o tipo de vínculo do trabalhador com a empresa ou obra.'],
  [/curso/i, 'Selecione o curso ou treinamento correspondente.'],
  [/norma|artigo|fonte|requisito/i, 'Informe a referência normativa ou requisito legal relacionado.'],
  [/perfil/i, 'Selecione ou informe o perfil de acesso que define as permissões do usuário.'],
  [/uid|tag|qr code/i, 'Informe o identificador lido na tag, NFC ou QR Code.'],
  [/vincular a|entidade/i, 'Selecione a entidade do sistema que será vinculada a esta identificação.'],
  [/item do question[aá]rio/i, 'Selecione a pergunta do questionário que será usada como critério.'],
  [/itens \(json\)/i, 'Cole a lista em JSON usando a estrutura esperada para importação em lote.'],
  [/epi/i, 'Selecione o equipamento de proteção individual relacionado.'],
  [/epc/i, 'Selecione o equipamento de proteção coletiva relacionado.'],
  [/fabricante/i, 'Informe o fabricante do equipamento, material ou item cadastrado.'],
  [/pe[cç]a|uniforme|tamanho/i, 'Informe a peça e o tamanho de uniforme relacionados ao movimento.'],
  [/les[aã]o/i, 'Descreva a lesão registrada, quando houver.'],
  [/consequ[eê]ncia/i, 'Informe a consequência do acidente ou incidente para o trabalhador e operação.'],
  [/atendimento/i, 'Descreva o atendimento prestado após a ocorrência.'],
  [/afastamento/i, 'Informe se houve afastamento decorrente da ocorrência.'],
  [/cat/i, 'Informe o número da CAT quando a comunicação tiver sido emitida.'],
  [/foto|logomarca|evid[eê]ncia|documento|arquivo|anexo/i, 'Anexe ou selecione o arquivo correspondente a este campo.'],
];

function textoDoRotulo(label: FluentFieldProps['label']): string | null {
  if (typeof label === 'string') return label;
  if (typeof label === 'number') return String(label);
  return null;
}

function dicaPadrao(label: FluentFieldProps['label'], required: FluentFieldProps['required']): string | null {
  const texto = textoDoRotulo(label);
  if (!texto) return null;
  const rotuloLimpo = texto.replace(/\s*\([^)]*\)\s*/g, ' ').replace(/\s+/g, ' ').trim();
  const dica = dicasExatas[texto.trim()] ?? dicasExatas[rotuloLimpo]
    ?? dicasPorRotulo.find(([padrao]) => padrao.test(rotuloLimpo))?.[1]
    ?? `Informe ${rotuloLimpo.toLocaleLowerCase('pt-BR')} de forma clara para identificar este registro depois.`;
  return required ? `${dica} Este campo é obrigatório.` : dica;
}

export function Field({ dica, label, required, hint, children, ...props }: FieldProps) {
  const conteudoDica = dica ?? dicaPadrao(label, required);
  const campo = (
    <FluentField {...props} label={label} required={required} hint={hint}>
      {children}
    </FluentField>
  );

  if (!conteudoDica) return campo;

  return (
    <SstTooltip conteudo={conteudoDica} titulo={textoDoRotulo(label) ?? 'Campo'} relacao="description" posicao="above-start">
      <div>{campo}</div>
    </SstTooltip>
  );
}
