// Estilos das três escalas de aba (pilar, módulo, interno) da peça Abas — spec §1.1, §3.
import { makeStyles, shorthands } from '@fluentui/react-components';
import { designTokens, tokensUi } from '../../tokens/tokens';

const base = {
  '& .fui-Tab::before': { display: 'none' },
  '& .fui-Tab::after': { display: 'none' },
  '& .fui-Tab__content': { color: 'inherit' },
  '& .fui-Tab__icon': { color: 'inherit' },
  '& .fui-Tab__icon svg': { width: '18px', height: '18px' },
};

export const useAbasStyles = makeStyles({
  pilar: {
    display: 'flex', flexWrap: 'nowrap', columnGap: '12px', rowGap: '10px',
    marginBottom: '18px',
    backgroundColor: designTokens.colorSurface,
    ...shorthands.border('1px', 'solid', designTokens.colorCardBorder),
    borderLeft: 'none',
    borderRight: 'none',
    ...shorthands.padding('8px', '16px'),
    overflowX: 'auto',
    scrollbarWidth: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
    '& .fui-Tab': {
      backgroundColor: 'transparent',
      ...shorthands.border('0', 'solid', 'transparent'),
      borderRadius: 0,
      color: designTokens.colorNeutralMedium,
      fontWeight: 600,
      fontSize: '14px',
      ...shorthands.padding('8px', '12px'),
      minHeight: 'auto', whiteSpace: 'nowrap', position: 'relative', top: '1px',
      transitionProperty: 'background-color, color', transitionDuration: tokensUi.duracao.rapido,
      gap: '8px',
    },
    '& .fui-Tab:hover': { backgroundColor: 'transparent', color: tokensUi.status.ok.tinta },
    '& .fui-Tab[aria-selected="true"]': { backgroundColor: 'transparent', color: tokensUi.status.ok.tinta, fontWeight: 800 },
    '& .fui-Tab[aria-selected="true"]:hover': { backgroundColor: 'transparent', color: tokensUi.status.ok.tinta },
    ...base,
  },
  modulo: {
    display: 'flex', flexWrap: 'nowrap', columnGap: '10px', rowGap: '8px', marginTop: '10px', marginBottom: '18px',
    backgroundColor: designTokens.colorSurface,
    ...shorthands.border('1px', 'solid', designTokens.colorCardBorder),
    ...shorthands.borderRadius(tokensUi.raio.lg),
    ...shorthands.padding('8px', '12px'),
    overflowX: 'auto',
    scrollbarWidth: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
    '& .fui-Tab': {
      backgroundColor: 'transparent', ...shorthands.border('0', 'solid', 'transparent'), borderRadius: 0,
      color: designTokens.colorNeutralMedium, fontWeight: 600, fontSize: '14px', ...shorthands.padding('8px', '12px'), minHeight: 'auto', whiteSpace: 'nowrap',
      transitionProperty: 'background-color, color', transitionDuration: tokensUi.duracao.normal,
      gap: '7px',
    },
    '& .fui-Tab:hover': { backgroundColor: 'transparent', color: tokensUi.status.ok.tinta },
    '& .fui-Tab[aria-selected="true"]': { backgroundColor: 'transparent', color: tokensUi.status.ok.tinta, fontWeight: 800 },
    '& .fui-Tab[aria-selected="true"]:hover': { backgroundColor: 'transparent', color: tokensUi.status.ok.tinta },
    ...base,
  },
  interno: {
    display: 'flex', flexWrap: 'nowrap', columnGap: '8px', rowGap: '6px', marginBottom: tokensUi.espaco.lg,
    backgroundColor: designTokens.colorSurface,
    ...shorthands.border('1px', 'solid', designTokens.colorCardBorder),
    ...shorthands.borderRadius(tokensUi.raio.md),
    ...shorthands.padding('6px', '10px'),
    overflowX: 'auto',
    scrollbarWidth: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
    '& .fui-Tab': {
      backgroundColor: 'transparent', ...shorthands.border('0', 'solid', 'transparent'), borderRadius: 0,
      color: designTokens.colorNeutralMedium, fontWeight: 600, fontSize: '13px', ...shorthands.padding('6px', '10px'), minHeight: 'auto', whiteSpace: 'nowrap',
      gap: '6px',
    },
    '& .fui-Tab:hover': { color: tokensUi.status.ok.tinta },
    '& .fui-Tab[aria-selected="true"]': { backgroundColor: 'transparent', color: tokensUi.status.ok.tinta, fontWeight: 800 },
    ...base,
  },
  contador: { marginLeft: '6px', opacity: 0.7, fontVariantNumeric: 'tabular-nums' },
});
